FROM mcr.microsoft.com/dotnet/sdk:9.0@sha256:3fcf6f1e809c0553f9feb222369f58749af314af6f063f389cbd2f913b4ad556 AS build
WORKDIR /App

# Copy everything
# COPY . ./
COPY ["talentbridge_webAPI.sln", "./"]
COPY ["talentbridge_webAPI.csproj", "./"]

# Restaura as dependências do projeto usando a solução
RUN dotnet restore talentbridge_webAPI.sln

# Copia o restante do código-fonte para o contêiner
COPY . .

# Build and publish a release
RUN dotnet publish talentbridge_webAPI.sln -o out

# Build runtime image
FROM mcr.microsoft.com/dotnet/aspnet:9.0@sha256:b4bea3a52a0a77317fa93c5bbdb076623f81e3e2f201078d89914da71318b5d8
WORKDIR /App
COPY --from=build /App/out .

# Verifique se o arquivo DLL foi copiado corretamente
RUN ls /App
ENTRYPOINT ["dotnet", "talentbridge_webAPI.dll"]